dir: ./

versions:
  kubernetes: 1.27.2
  crictl: 1.27.0
  cni-plugins: 1.3.0
  containerd: 1.5.7
  runc: 1.1.7

  openebs: 3.6.0
  contour: 1.18.0

  images:
    - registry.k8s.io/coredns/coredns:v1.10.1
    - registry.k8s.io/etcd:3.5.7-0
    - registry.k8s.io/pause:3.9
    - docker.io/envoyproxy/envoy:v1.26.1
    - ghcr.io/projectcontour/contour:v1.25.0
